### ISSUE TITLE
Generate Avro Schema from Data Classes

### ISSUE THREAD

**Issue by psilos** [thake/avro4k-compiler#1]
Hello,

I just run into this plug-in while trying to generate Avro Schema in an automated way from Data Classes, I have been using Avro4K for the definition and manual generation of the schema but was wondering whether your plug-in supports or can be extended to support the opposite, generating avro schema from Avro4K data classes.

**Comment by darmstrong1** [comment]
This project will do that: [https://github.com/avro-kotlin/avro4k](https://github.com/avro-kotlin/avro4k)
